### ISSUE TITLE
The PayPal's `PaymentStatus` transaction is undocumented

### ISSUE THREAD

**Issue by dmitrii-fediuk** [mage2pro/alphacommercehub#52]
- [[AlphaCommerceHub] Where is the request and response parameters specification for the PayPal's `PaymentStatus` transaction?](https://mage2.pro/t/topic/4991)
- #48 (PayPal: implement the `PaymentStatus` transaction)

**Comment by scuba78** [comment]
Please see the API Explorer section of the Developer Center:

http://developer.alphacommercehub.com.au/api-explorer/10/paypal---payment-status

**Comment by dmitrii-fediuk** [comment]
OK, thanks.
I saw this page, but did not regard it as the  specification because it lacks of some important details. 
I will formulate my remarks as separate topics.

**Comment by dmitrii-fediuk** [comment]
I have formulated my remarks here:

- [Where is the response parameters specification for the PayPal's `PaymentStatus` transaction?](https://mage2.pro/t/topic/4991/3)
- [How can I know `MerchantID` (which is required for the `PaymentStatus` and `CapturePayment` PayPal transactions) if a `SuccessURL` response to a PayPal payment does not provide it?](https://mage2.pro/t/topic/5017)

**Comment by dmitrii-fediuk** [comment]
[A PayPal's `PaymentStatus` API request, and a response to it](https://mage2.pro/t/5120).
