### ISSUE TITLE
The PayPal's `CapturePayment` transaction is undocumented

### ISSUE THREAD

**Issue by dmitrii-fediuk** [mage2pro/alphacommercehub#53]
It blocks me from implementing #49 (PayPal: implement the `CapturePayment` transaction).

[[AlphaCommerceHub] Where is the request and response parameters specification for the PayPal's `CapturePayment` transaction?](https://mage2.pro/t/topic/4992)

**Comment by scuba78** [comment]
Please see the API Explorer section of the Developer Center: 

http://developer.alphacommercehub.com.au/api-explorer/11/paypal---capture-payment

**Comment by dmitrii-fediuk** [comment]
OK, thanks.
I saw this page, but did not regard it as the  specification because it lacks of some important details. 
I will formulate my remarks as separate topics.

**Comment by dmitrii-fediuk** [comment]
I have formulated my remarks here:

- [Where is the response parameters specification for the PayPal's `CapturePayment` transaction?](https://mage2.pro/t/topic/4992/2)
- [How can I know `MerchantID` (which is required for the `PaymentStatus` and `CapturePayment` PayPal transactions) if a `SuccessURL` response to a PayPal payment does not provide it?](https://mage2.pro/t/topic/5017)
